{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codeborne",
    "module": "selenide",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "net.bytebuddy",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.codeborne",
          "module": "selenide-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "selenide-6.1.2.jar",
          "url": "selenide-6.1.2.jar",
          "size": 22799,
          "sha512": "93dfd306c4a2a609f5ed4f2260f4900cde6d38b968784173c79b16287ed6dd900ea9902c3cc20790ebe4844b3d835812d92e2e74d2e3fb0a944243573a3123ec",
          "sha256": "607848e6c8fda17de6d1a58ce57614ef42acad1aa67321a5cddeb4e228df4f7d",
          "sha1": "14e999f98b546f7d8e14f52d01cfb92f0314c1a8",
          "md5": "533dbdb54d0613988afa0299576285d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "net.bytebuddy",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.codeborne",
          "module": "selenide-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "selenide-6.1.2.jar",
          "url": "selenide-6.1.2.jar",
          "size": 22799,
          "sha512": "93dfd306c4a2a609f5ed4f2260f4900cde6d38b968784173c79b16287ed6dd900ea9902c3cc20790ebe4844b3d835812d92e2e74d2e3fb0a944243573a3123ec",
          "sha256": "607848e6c8fda17de6d1a58ce57614ef42acad1aa67321a5cddeb4e228df4f7d",
          "sha1": "14e999f98b546f7d8e14f52d01cfb92f0314c1a8",
          "md5": "533dbdb54d0613988afa0299576285d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "selenide-6.1.2-javadoc.jar",
          "url": "selenide-6.1.2-javadoc.jar",
          "size": 77061,
          "sha512": "d20cc9aef65862b810743f8bf94369847f1553ebfe89e1f78d1bf9464ad5bf2884632e0697e2f57c2a4f9dec778bd0eec788d16d6a4349886c5fb6f8b9dac1fd",
          "sha256": "35c185b88c1610c5bee3e620433c5a243f9ea7ce232a62226e6a645a342d969b",
          "sha1": "896bf620d8352cf36aaeb294e36e85b60652c64f",
          "md5": "6e6b17788d9917a8075ce2a332629071"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "selenide-6.1.2-sources.jar",
          "url": "selenide-6.1.2-sources.jar",
          "size": 22110,
          "sha512": "17a6824c5d3720ee64323ec993158f10a765587fe4eaebecee07964d28202a75fa8029406a8e33682c9011128e0d37c912eb0a8240e9776e0b0c0fc73f0399e3",
          "sha256": "ff0831457fce5d079b3855c1785f53a960bbd793fd43c68f8db60b376cb471a5",
          "sha1": "62f5bdff82fca248c9f332da59eacb67e9b88470",
          "md5": "1a9a8a277c34b7178a9af99d4ba27e51"
        }
      ]
    }
  ]
}
